name: rust
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Run
        run: make -C rust/clippy run
      - uses: shogo82148/actions-mutex@v1
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: rust/clippy/output.txt
          commit_message: Apply changes

  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Run
        run: make -C rust/cargo-audit run
      - uses: shogo82148/actions-mutex@v1
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: rust/cargo-audit/output.txt
          commit_message: Apply changes

  cargo-spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Run
        run: make -C rust/cargo-spellcheck run
      - uses: shogo82148/actions-mutex@v1
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: rust/cargo-spellcheck/output.txt
          commit_message: Apply changes

  cargo-expand:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Run
        run: make -C rust/cargo-expand run
      - uses: shogo82148/actions-mutex@v1
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: rust/cargo-expand/output.txt
          commit_message: Apply changes
