name: run
on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  rust:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: [clippy, cargo-audit, cargo-spellcheck, cargo-expand]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run
        run: make -C rust/${{ matrix.tool }} run
        continue-on-error: true

  commit:
      runs-on: ubuntu-latest
      needs: [rust]
      steps:
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update benchmarks
