name: rust
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: make -C rust/clippy run
        
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: make -C rust/cargo-audit run
